use serde::Serialize;
use std::path::PathBuf;
use std::process::Command;
use tauri::State;
use tracing::info;

use crate::utils::errors::WeaveError;
use crate::AppState;

/// llama-swap router base URL — see llama.nix (`llamaPort = "8080"`).
pub const LLAMA_SWAP_BASE_URL: &str = "http://127.0.0.1:8080";
pub const LLAMA_SWAP_CHAT_URL: &str = "http://127.0.0.1:8080/v1/chat/completions";
/// Systemd user unit Weave manages — the same one `llm service start/stop`
/// controls; the config generator lives in the unit's ExecStart, so Weave
/// never writes config.yaml itself.
pub const LLAMA_SWAP_UNIT: &str = "llama-swap.service";
/// Readiness budget after `systemctl --user start` (config regeneration is
/// fast; a stale port holder or missing models makes the unit fail).
const READY_POLLS: u32 = 33;
const READY_POLL_INTERVAL: std::time::Duration = std::time::Duration::from_millis(300);

#[derive(Debug, Clone, Serialize)]
pub struct LlamaSwapStatus {
    pub active: bool,
    pub model_count: usize,
    pub models: Vec<String>,
    pub last_error: Option<String>,
}

/// `~/.config/llama-swap/config.yaml` — generated by the unit's ExecStart on
/// every start (authoritative model-id source; byte-for-byte what the router
/// expects). Absent file = service never started = empty provider, not error.
pub fn config_path() -> Result<PathBuf, WeaveError> {
    let home = dirs::home_dir()
        .ok_or_else(|| WeaveError::ConfigError("Cannot find home directory".to_string()))?;
    Ok(home.join(".config").join("llama-swap").join("config.yaml"))
}

/// Parse model ids out of the generated config — the `  "<id>":` lines under
/// the `models:` section. Line-based on purpose: the file is machine-generated
/// by the user's own Nix script with a fixed shape, and we avoid a YAML
/// dependency. A quoted key with nothing after the colon (`"<id>":`) is a
/// model id; nested keys like `proxy: "..."` never start with a quote, and
/// lines before `models:` are ignored.
fn parse_config_models(content: &str) -> Vec<String> {
    let mut in_models = false;
    content
        .lines()
        .map(str::trim)
        .filter(|l| {
            if *l == "models:" {
                in_models = true;
                return false;
            }
            in_models && l.starts_with('"') && l.ends_with("\":")
        })
        .filter_map(|l| l[1..l.len() - 2].to_string().into())
        .collect()
}

/// Live read of the authoritative model list. Never cached — `llm dl` +
/// `llm service restart` regenerates the file and Weave must see it
/// immediately. Missing file (service never started) → empty, not error.
pub fn list_models() -> Result<Vec<String>, WeaveError> {
    let path = config_path()?;
    if !path.exists() {
        return Ok(Vec::new());
    }
    let content = std::fs::read_to_string(&path)?;
    Ok(parse_config_models(&content))
}

/// The context window every model runs with — parsed live from the
/// generated config's `-c NNNN` arg (the unit's generator pins it once for
/// all models; the VRAM-bound ceiling is infra-owned, Weave only needs to
/// know it). Fallback 8192 when unparseable/absent.
pub fn context_size() -> usize {
    let content = match config_path().and_then(|p| std::fs::read_to_string(p).map_err(Into::into)) {
        Ok(c) => c,
        Err(_) => return 8192,
    };
    context_size_from_content(&content)
}

fn context_size_from_content(content: &str) -> usize {
    for line in content.lines() {
        if let Some(pos) = line.find("-c ") {
            let rest = &line[pos + 3..];
            let num: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
            if let Ok(n) = num.parse::<usize>() {
                if n > 0 {
                    return n;
                }
            }
        }
    }
    8192
}

/// Router reachability — `GET /v1/models` returns the catalog without
/// loading any model (loading is lazy, per request, on the router side).
async fn router_active(client: &reqwest::Client) -> bool {
    match client
        .get(format!("{}/v1/models", LLAMA_SWAP_BASE_URL))
        .timeout(std::time::Duration::from_secs(2))
        .send()
        .await
    {
        Ok(resp) => resp.status().is_success(),
        Err(_) => false,
    }
}

fn systemctl(args: &[&str]) -> Result<std::process::Output, WeaveError> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .map_err(|e| WeaveError::LocalLlmNotAvailable(format!("systemctl failed: {}", e)))
}

/// Last N lines of the unit's journal — the actionable error surface for
/// start failures ("Address already in use", "No .gguf model found", …).
fn journal_tail(lines: usize) -> String {
    match Command::new("journalctl")
        .arg("--user")
        .arg("-u")
        .arg(LLAMA_SWAP_UNIT)
        .arg("-n")
        .arg(lines.to_string())
        .arg("--no-pager")
        .arg("-o")
        .arg("short")
        .output()
    {
        Ok(out) => {
            let text = String::from_utf8_lossy(&out.stdout).trim().to_string();
            if text.is_empty() {
                "(journal is empty — the unit may never have started)".to_string()
            } else {
                text
            }
        }
        Err(_) => "(journalctl could not be run)".to_string(),
    }
}

/// Ensure the router is up: active → done; otherwise `systemctl --user start`
/// (same call `llm service start` makes) and poll readiness. On failure the
/// error carries the journal tail so the user knows exactly what to fix.
pub async fn ensure_ready() -> Result<(), WeaveError> {
    let client = reqwest::Client::new();
    if router_active(&client).await {
        return Ok(());
    }

    info!("Starting {} …", LLAMA_SWAP_UNIT);
    let output = systemctl(&["start", LLAMA_SWAP_UNIT])?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(WeaveError::LocalLlmNotAvailable(format!(
            "llama-swap failed to start: {}\n{}",
            stderr.trim(),
            journal_tail(12)
        )));
    }

    for _ in 0..READY_POLLS {
        if router_active(&client).await {
            info!("{} ready", LLAMA_SWAP_UNIT);
            return Ok(());
        }
        tokio::time::sleep(READY_POLL_INTERVAL).await;
    }

    Err(WeaveError::LocalLlmNotAvailable(format!(
        "llama-swap not ready after {:.1}s. Last journal lines:\n{}",
        READY_POLLS as f64 * READY_POLL_INTERVAL.as_secs_f64(),
        journal_tail(12)
    )))
}

fn set_last_error(app_state: &AppState, error: Option<String>) {
    let mut guard = app_state.llama_swap_last_error.lock();
    *guard = error;
}

#[tauri::command]
pub async fn llama_swap_status(
    app_state: State<'_, AppState>,
) -> Result<LlamaSwapStatus, WeaveError> {
    let active = {
        let client = reqwest::Client::new();
        router_active(&client).await
    };
    let models = list_models()?;
    let last_error = app_state.llama_swap_last_error.lock().clone();
    Ok(LlamaSwapStatus {
        active,
        model_count: models.len(),
        models,
        last_error,
    })
}

#[tauri::command]
pub async fn llama_swap_start(
    app_state: State<'_, AppState>,
) -> Result<LlamaSwapStatus, WeaveError> {
    match ensure_ready().await {
        Ok(()) => set_last_error(&app_state, None),
        Err(e) => set_last_error(&app_state, Some(e.to_string())),
    }
    llama_swap_status(app_state).await
}

#[tauri::command]
pub async fn llama_swap_stop(
    app_state: State<'_, AppState>,
) -> Result<LlamaSwapStatus, WeaveError> {
    info!("Stopping {} …", LLAMA_SWAP_UNIT);
    let output = systemctl(&["stop", LLAMA_SWAP_UNIT])?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(WeaveError::LocalLlmNotAvailable(format!(
            "llama-swap failed to stop: {}",
            stderr.trim()
        )));
    }
    llama_swap_status(app_state).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_config_models() {
        let sample = r#"# Auto-generated
healthCheckTimeout: 500
logLevel: info
startPort: 10100
models:
  "deepseek-r1-0528-qwen3-8b-q4_k_m":
    proxy: "http://127.0.0.1:${PORT}"
    cmd: >
      llama-server -m ".../DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf"
    ttl: 300
  "gemma-4-12b-it-qat-ud-q4_k_xl":
    proxy: "http://127.0.0.1:${PORT}"
"#;
        let models = parse_config_models(sample);
        assert_eq!(
            models,
            vec![
                "deepseek-r1-0528-qwen3-8b-q4_k_m".to_string(),
                "gemma-4-12b-it-qat-ud-q4_k_xl".to_string()
            ]
        );
    }

    #[test]
    fn test_parse_config_models_empty() {
        assert!(parse_config_models("").is_empty());
        assert!(parse_config_models("models:\n  nothing here\n").is_empty());
    }

    #[test]
    fn test_parse_config_models_ignores_preamble() {
        // The doc-comment header contains `"key":` patterns that must not be
        // picked up outside the models: section.
        let sample = "healthCheckTimeout: 500\nlogLevel: info\n\"version\":\nmodels:\n  \"a\":\n";
        assert_eq!(parse_config_models(sample), vec!["a".to_string()]);
    }

    #[test]
    fn test_parse_config_models_ignores_non_ids() {
        let sample = "  \"proxy\": \"http://x\"\n    proxy: \"http://127.0.0.1:${PORT}\"\n    cmd: >\n      llama-server -m \"...\"\n";
        // Only `"<id>":` keys are ids — `"proxy": "http://x"` has content
        // after the colon, and unquoted nested keys are skipped entirely.
        assert!(parse_config_models(sample).is_empty());
    }

    #[test]
    fn test_config_path_points_at_user_config() {
        let path = config_path().unwrap();
        assert!(path.ends_with(".config/llama-swap/config.yaml"));
    }

    #[test]
    fn test_context_size_parses_c_from_cmd() {
        let sample =
            "models:\n  \"m\":\n    cmd: >\n      llama-server -m \"...\" -c 32768 --threads 12\n";
        assert_eq!(context_size_from_content(sample), 32768);
        assert_eq!(context_size_from_content("no -c here"), 8192);
        assert_eq!(context_size_from_content(""), 8192);
    }
}
